<template>
  <div class="text-img-container">
    <div class="img-box" :style="{ animationPlayState: isAni ? 'running' : 'paused' }">
      <div class="text">
        Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex.
        Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript
        state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework
        and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use
        case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If
        you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your
        stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay
        useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that
        can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the
        component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and
        provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template
        syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the
        rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may
        vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA)
        Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to
        follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge
        about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the
        problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an
        HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue
        (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here
        is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state
        changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and
        ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use
        case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If
        you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your
        stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay
        useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that
        can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the
        component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and
        provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template
        syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the
        rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may
        vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA)
        Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to
        follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge
        about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the
        problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an
        HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue
        (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here
        is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state
        changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and
        ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use
        case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If
        you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user
        interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features
        of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already
        have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development.
        But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step
        Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only
        require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more
        detail in Ways of Using Vue. Despite the flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a
        veteran, you can pick the optimal way to leverage Vue based on the problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most
        build-tool-enabled Vue projects, we author Vue components using an HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a
        single file. Here's the previous example, written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you
        efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on
        JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a
        high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed
        to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site
        Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue can be
        used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these
        concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on
        top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative
        Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions -
        don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is
        extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web
        Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML
        and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of
        Using Vue. Despite the flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can
        pick the optimal way to leverage Vue based on the problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled
        Vue projects, we author Vue components using an HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the
        previous example, written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user
        interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity:
        Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of
        what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and
        incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting
        desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue can be used in different ways:
        Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating,
        don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML,
        CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends
        standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover
        every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the
        things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page
        Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge,
        and you should be able to follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the
        flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to
        leverage Vue based on the problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author
        Vue components using an HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example,
        written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be
        they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue
        automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what
        Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally
        adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop,
        mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue extends standard HTML with a template syntax
        that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of
        the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary
        drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA)
        Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to
        follow along without being an expert in any of these. Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting
        desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue (pronounced /vjuː/, like view) is a
        JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above
        example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the
        DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common
        features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways:
        Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating,
        don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what
        these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more
        ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to
        your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript),
        template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and
        component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to
        declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation.
        For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form
        and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side
        Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being
        an expert in any of these. Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have
        questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But
        the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step
        Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only
        require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack /
        Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along
        without being an expert in any of these. Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user
        interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity:
        Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of
        what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and
        incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting
        desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. If you are an experienced developer
        interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if you are just a beginner
        now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the problems you are trying to solve, while retaining the same productivity. This is why we call Vue
        "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC).
        A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on
        top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative
        Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions -
        don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is
        extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web
        Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML
        and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state
        changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and
        ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use
        case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If
        you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue can be used in different ways: Enhancing static HTML without a build step Embedding
        as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic
        HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and
        component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to
        declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation.
        For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form
        and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side
        Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being
        an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge about how Vue works is
        shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the problems you are trying to
        solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an HTML-like file format called
        Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue (pronounced /vjuː/, like view)
        is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above
        example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the
        DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common
        features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways:
        Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating,
        don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript
        state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level
        understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be
        flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation
        (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue can be used in
        different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts
        intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of
        standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering:
        Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We
        will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse
        - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any
        page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript
        knowledge, and you should be able to follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite
        the flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way
        to leverage Vue based on the problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we
        author Vue components using an HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous
        example, written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user
        interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity:
        Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of
        what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and
        incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting
        desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue extends standard HTML with a
        template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail
        in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the
        web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application
        (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able
        to follow along without being an expert in any of these. Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG)
        Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue (pronounced /vjuː/, like
        view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The
        above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently
        updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most
        of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in
        different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts
        intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious
        about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to
        tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and
        adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic
        (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative
        and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us
        to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the
        documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary
        drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA)
        Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to
        follow along without being an expert in any of these. Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes
        happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed
        in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static
        HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The
        tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application
        (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able
        to follow along without being an expert in any of these. Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you
        efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on
        JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a
        high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed
        to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site
        Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. If you are
        an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge about how Vue works is shared across all these use cases. Even if
        you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the problems you are trying to solve, while retaining the same productivity.
        This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an HTML-like file format called Single-File Component (also known as *.vue
        files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user
        interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features
        of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already
        have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development.
        But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step
        Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only
        require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks
        JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a
        framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending
        on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the
        terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue can be used in different ways: Enhancing static HTML without a build
        step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only
        require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these. Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a
        declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax
        that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of
        the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary
        drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA)
        Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to
        follow along without being an expert in any of these. If you are an experienced developer interested in how to best integrate Vue into your stack, or you are curious about what these terms mean, we discuss them in more detail in Ways of Using Vue. Despite the flexibility, the core knowledge
        about how Vue works is shared across all these use cases. Even if you are just a beginner now, the knowledge gained along the way will stay useful as you grow to tackle more ambitious goals in the future. If you are a veteran, you can pick the optimal way to leverage Vue based on the
        problems you are trying to solve, while retaining the same productivity. This is why we call Vue "The Progressive Framework": it's a framework that can grow with you and adapt to your needs. Single-File Components In most build-tool-enabled Vue projects, we author Vue components using an
        HTML-like file format called Single-File Component (also known as *.vue files, abbreviated as SFC). A Vue SFC, as the name suggests, encapsulates the component's logic (JavaScript), template (HTML), and styles (CSS) in a single file. Here's the previous example, written in SFC format: Vue
        (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex. Here
        is a minimal example: The above example demonstrates the two core features of Vue: Declarative Rendering: Vue extends standard HTML with a template syntax that allows us to declaratively describe HTML output based on JavaScript state. Reactivity: Vue automatically tracks JavaScript state
        changes and efficiently updates the DOM when changes happen. You may already have questions - don't worry. We will cover every little detail in the rest of the documentation. For now, please read along so you can have a high-level understanding of what Vue offers. Vue is a framework and
        ecosystem that covers most of the common features needed in frontend development. But the web is extremely diverse - the things we build on the web may vary drastically in form and scale. With that in mind, Vue is designed to be flexible and incrementally adoptable. Depending on your use
        case, Vue can be used in different ways: Enhancing static HTML without a build step Embedding as Web Components on any page Single-Page Application (SPA) Fullstack / Server-Side Rendering (SSR) Jamstack / Static Site Generation (SSG) Targeting desktop, mobile, WebGL, and even the terminal If
        you find these concepts intimidating, don't worry! The tutorial and guide only require basic HTML and JavaScript knowledge, and you should be able to follow along without being an expert in any of these.
      </div>
      <!-- <img src="@/assets/images/textures/dance-man.png" alt="" /> -->
    </div>
  </div>
</template>
<script setup>
const name = '文字图片'
const isAni = ref(true)
onMounted(() => {
  document.querySelector('.img-box').addEventListener('dblclick', () => {
    isAni.value = !isAni.value
  })
})
</script>

<style lang="scss" scoped>
@keyframes ani {
  0% {
    font-size: 12px;
    line-height: 12px;
    // filter: saturate(2) contrast(20) grayscale(1);
    // height: 90%;
    // width: 70%;
    // border-radius: 50px;
  }
  100% {
    font-size: 40px;
    line-height: 40px;
    // filter: saturate(1) contrast(1) grayscale(0);
    // width: 100%;
    // height: 100%;
    // border-radius: 0;
  }
}

.text-img-container {
  .img-box {
    // background-color: #ffffff;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    width: 100vw;
    height: 100vh;
    transition: all 0.5s;
    // border-radius: 100%;
    overflow: hidden;
    animation: ani ease-in-out 10s alternate infinite;
    &.ani {
    }

    .text {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      // font-size: 20px;
      // line-height: 20px;
      background: url('@/assets/images/textures/hqh.jpg') no-repeat top center / cover;
      background-attachment: fixed;
      color: transparent;
      background-clip: text;
      -webkit-background-clip: text;
      filter: saturate(2) contrast(10) grayscale(1);
      // transition: all 0.5s;

      box-shadow: inset 0px 0px 30px 10px black;
      word-break: break-all;
      // &:hover {
      //   transform: scale(1.5);
      // }
    }
  }
}
</style>
